project:
  type: website

website:
  title: "ML Blog"
  description: "Illustrated tutorials about LLMs, Computer Vision, Software engineer. Curly hair creative technologist descending the gradient."
  site-url: https://m0saan.github.io/blog
  navbar:
    left:
      - text: "{{< fa atom >}} Projects"
        file: projects.qmd
      - text: "{{< fa address-card >}} About"
        file: about.qmd
    right:
      - text: "@m0saan"
        icon: twitter
        href: https://twitter.com/boustta_mo
      - icon: github
        href: https://github.com/m0saan
      - icon: linkedin
        href: https://www.linkedin.com/in/mohammad-boustta-68b2a4191/
    pinned: false
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2023, M0saab" 

format:
  html:
    page-layout: article
    theme: [cosmo, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true

comments:
  utterances:
    repo: https://github.com/m0saan/portfolio